### ISSUE TITLE
CMake error: cannot find "FindLibRDKafka.cmake"

### ISSUE THREAD

**Issue by roalz** [meox/KClient#1]
I'm looking at KClient project to study a real project using CMake ExternalProject stuff.

I'm trying to build with CMake but I get the following error (extracted from full log): 

"CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindLibRDKafka.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibRDKafka", but CMake did not find one.
<omissis>
-- Configuring incomplete, errors occurred!"

I just noticed that the root CMakeLists.txt adds "~/cmake/Modules" to CMAKE_MODULE_PATH, maybe the missing find module is there?
If this is the case, would it be a good practice to add the FindLibRDKafka.cmake to a ./cmake directory in this repo?
If not (i.e. the Find or Config module should be taken from somewhere else), would you mind adding this info to the README.md under ### compile ?

**Comment by meox** [comment]
I'm working on add this lib as external library.
I hope to complete this task in the following days.

**Comment by meox** [comment]
relative branch: librdkafka_ext_lib

**Comment by meox** [comment]
merged
